version: "3.4"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    restart: unless-stopped
    hostname: qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022
      - WEBUI_PORT=8988
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - 6881:6881
      - 8988:8988

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    hostname: jackett
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ./config/timezone:/etc/localtime:ro
      - ./downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ./config/jackett:/config # config files
    ports:
      - 9117:9117

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    hostname: sonarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ./config/timezone:/etc/localtime:ro
      - ./config/sonarr:/config # config files
      - ./downloads/complete/tv:/tv # tv shows folder
      - ./downloads/complete/anime:/anime # tv shows folder
      - ./downloads:/downloads # download folder
    ports:
      - 8989:8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    hostname: radarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ./config/timezone:/etc/localtime:ro
      - ./config/radarr:/config # config files
      - ./downloads/complete/movies:/movies # movies folder
      - ./downloads:/downloads # download folder
    ports:
      - 7878:7878

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    hostname: bazarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ./config/bazarr:/config # config files
      - ./downloads/complete/movies:/movies # movies folder
      - ./downloads/complete/tv:/tv # tv shows folder
      - ./downloads/complete/anime:/anime # anime shows folder
    ports:
      - 6767:6767
